[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --browser chromium
    --alluredir=allure-results
    --log-cli-level=INFO
    --capture=no
markers =
    smoke: Quick smoke tests
    regression: Full regression tests
log_cli = true
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %H:%M:%S

